import type { Metadata } from "next";
import "./globals.css";
import { spaceMono, ibmPlexMono, lexendDeca } from "./fonts";
import { MagneticProvider } from "@/context/MagneticContext";
import { HardwareCapabilityProvider } from "@/context/HardwareCapabilityContext";
import { ViewportHeightFix } from "@/components/viewport-fix";

export const metadata: Metadata = {
  title: "Noah Paige | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${spaceMono.className} ${ibmPlexMono.className} ${lexendDeca.className}`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Doto:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-lexend-deca overflow-hidden isolate">
        <ViewportHeightFix />
        <HardwareCapabilityProvider>
          <MagneticProvider>{children}</MagneticProvider>
        </HardwareCapabilityProvider>
      </body>
    </html>
  );
}
